In [3]:
a=24
print(a)
print(type(a))

24
<class 'int'>


In [13]:
inp=input("enter the number")
print("i am",inp,"years old")


enter the number 2


i am 2 years old


In [15]:
print("i am",a,"years old")

i am 24 years old


In [21]:
num1=int(input("enter a number"))
num2=int(input("enter a another number"))
s=num1-num2
print("the difference is",s)


enter a number 6
enter a another number 3


the difference is 3


In [23]:
#airthmetic operation
a=10
b=11
print(a+b)
print(a-b)
print(a*b)
print(a/b) #display floating point
print(a%b)
print(a**b)
print(a//b) #display exact value


21
-1
110
0.9090909090909091
10
100000000000
0


In [27]:
a=1
b=3
print(a**b)

1


In [31]:
password="spandana@123"
p=input("enter a password")
if p==password:
    print("welcome")
else:
    print("try again")


enter a password 123


try again


In [37]:
password="spandana"
pin=1234
p=input("enter a password")
pi=int(input("enter a pin"))

if p==password and pi==pin:
    print("welcome")
else:
    print("try again")
     
   




enter a password spandana
enter a pin 1234


welcome


In [41]:
s="hello how are you"
print(s[0:-5])

hello how ar


In [45]:
s="hello how are you"
print(s[0::4])

howeu


In [51]:
s="hello how are you"
for i in range(0,5):
 print(s[i])

h
e
l
l
o


In [57]:
def factorial(n):
    

    return 1 if (n==1 or n==0) else n * factorial(n - 1) 
num = 5
print("Factorial of",num,"is",factorial(num))

Factorial of 5 is 120


In [61]:
fact=1
i=1
while i<=5:
    fact*=i
    i=i+1
print(fact)

120


In [72]:
sum=0
i=0
while i<=5:
    sum+=i
    i=i+1
    print(sum)

0
1
3
6
10
15


collectons

In [76]:
#lists mutable,homogenious,duplicates,accepts
list1 = [2,3,4,"apple"]
print(list1)

[2, 3, 4, 'apple']


In [78]:
#adding elements in the list
list1.append("hello")
print(list1)


[2, 3, 4, 'apple', 'hello']


In [80]:
list1.insert(3,"boll") #insert(index,element)
print(list1)

[2, 3, 4, 'boll', 'apple', 'hello']


In [82]:
list1.remove("boll") #element
print(list1)

[2, 3, 4, 'apple', 'hello']


In [84]:
list1.pop(2) #index
print(list1)

[2, 3, 'apple', 'hello']


In [86]:
list2=[2,3,4,6,7]
list3=["amu","suma","ram"]
print(list2+list3)

[2, 3, 4, 6, 7, 'amu', 'suma', 'ram']


In [90]:
list5=[22,45,12,34,29] #sort
list5.sort(reverse=True)
list5

[45, 34, 29, 22, 12]

In [96]:
#difference diff sort and sorted
list6=[2,6,4,8,3,9]
list7=sorted(list6) #changes are not reflected in original list
list7 #need to store changes in diff list


[2, 3, 4, 6, 8, 9]

In [98]:
list6

[2, 6, 4, 8, 3, 9]

In [104]:
list4=[2,4,7,8]
list4

[2, 4, 7, 8]

In [106]:
list2.extend(list4) #extend the list
list2


[2, 3, 4, 6, 7, 2, 4, 7, 8]

In [ ]:
# for when element is over the loop should be comming out
# while when condition is over the loop should come out

In [108]:
for i in list6: #squareing a elements
    print(i*i)

4
36
16
64
9
81


In [110]:
listnew=[i*i for i in list6]
listnew

[4, 36, 16, 64, 9, 81]

In [3]:
list6=[1,2,3,4,5,6,7,8]
s=[]
for i in list6:
    if i>5:
        s.append(i*i)
print(s)


[36, 49, 64]


In [5]:
#newlist=input for if
slc=[i*i for i in list6 if i>5]
slc

[36, 49, 64]

In [1]:
marks=[50,60,70,80,90,100]
grades=[]

for i in marks:
    if i>90:
        grades.append("A")
    else:
        grades.append("B")

In [4]:
grades

['B', 'B', 'B', 'B', 'B', 'A']

In [8]:
gradeslc=["A" if i>90 else "B" for i in marks]
gradeslc

['B', 'B', 'B', 'B', 'B', 'A']

#if the salary is more than 50000 reduce 10% tax else reduce 5% tax and save the remaing salary in new list

In [21]:
sal=[1500,70000,10000,45000,1200]
final=[]
for i in sal:
    if i>50000:
        tax=i*0.1
        total=i-tax
        final.append(total)
    else:
        tax=i*0.05
        total=i-tax
        final.append(total)
final
    
        

[1425.0, 63000.0, 9500.0, 42750.0, 1140.0]

In [23]:
salslc=[i-i*0.1 if i>50000 else i-i*0.05 for i in sal] #comprention function
salslc

[1425.0, 63000.0, 9500.0, 42750.0, 1140.0]

In [27]:
list2=[3,4,5,6,7] #zip function
list3=[2,1,9,7,2]
for i,j in zip(list2,list3):
    print(i+j)

5
5
14
13
9


Tuple

In [1]:
tup1=[23,45,"spandu",49,99]
tup1

[23, 45, 'spandu', 49, 99]

In [3]:
tup2=[23,67,87.12,43]
print(max(tup2))
print(min(tup2))
print(len(tup2

87.12
23
4


In [5]:
tup3=sorted(tup2)
tup3

[23, 43, 67, 87.12]

dictionary

In [9]:
dict1={1:"john",2:"Ram",3:"sneha"}
dict1

{1: 'john', 2: 'Ram', 3: 'sneha'}

In [25]:
dict2={'namme':"spandana",'hobbies':['eating','reading','dancing']}
print(dict2['hobbies'])

['eating', 'reading', 'dancing']


In [27]:
dict2['hobbies'][1]

'reading'

In [29]:
#set ,no duplicate values
s1={12,13,56,87,12,22}
s1

{12, 13, 22, 56, 87}

In [3]:
import numpy as np

In [5]:
#Array
ar1=np.array([21,31,26,76])
ar2=np.array([29,47,43,98])
ar1+ar2

array([ 50,  78,  69, 174])

In [7]:
ar3=np.ones((2,3))
print(ar3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
ar4=np.ones((4,5))
print(ar4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
ar5=np.eye((4))
print(ar5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
ar6=np.arange(5)
print(ar6)

[0 1 2 3 4 5]


In [19]:
ar6=np.arange(5,50)
print(ar6)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
ar6=np.arange(8,1001,8) #start, stop, step
print(ar6)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [27]:
np.ndim(ar3)

2

In [29]:
np.shape(ar4)

(4, 4)

In [31]:
#2D
ar8=np.array([[3,4,5],[1,2,3]])
print(ar8)

[[3 4 5]
 [1 2 3]]


In [37]:
ar9=np.array([[[3,4,5],[1,2,3]],[[7,8,9],[4,5,6]]])
print(ar9)

[[[3 4 5]
  [1 2 3]]

 [[7 8 9]
  [4 5 6]]]


In [ ]:
statistics

In [39]:
n=np.array([89,43,67,87,24])

In [43]:
Avg=np.mean(n)
print(Avg)

62.0


In [45]:
med=np.median(n)
print(med)

67.0


In [47]:
sd=np.std(n)
print(sd)

25.234896472940004
